 package API;

import java.util.Random;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class RandomKit {
	
	
	
	public static void randomKit(Player player) {
		

		ItemStack SwordI = new ItemStack(Material.IRON_SWORD,1 );
		ItemStack SwordD = new ItemStack(Material.DIAMOND_SWORD,1 );
		ItemStack SwordS = new ItemStack(Material.STONE_SWORD,1 );
		ItemStack Rod = new ItemStack(Material.FISHING_ROD, 1);
		ItemStack Bow = new ItemStack(Material.BOW, 1);
		ItemStack Arrow24 = new ItemStack(Material.ARROW, 24);
		ItemStack Arrow8 = new ItemStack(Material.ARROW, 8);
		ItemStack Arrow16 = new ItemStack(Material.ARROW, 16);
		ItemStack Arrow36 = new ItemStack(Material.ARROW, 24);
		ItemStack IronH = new ItemStack(Material.IRON_HELMET, 1);
		ItemStack IronC = new ItemStack(Material.IRON_CHESTPLATE, 1);
		ItemStack IronL = new ItemStack(Material.IRON_LEGGINGS, 1);
		ItemStack IronB = new ItemStack(Material.IRON_BOOTS, 1);
		ItemStack DiamondH = new ItemStack(Material.DIAMOND_HELMET, 1);
		ItemStack DiamondC = new ItemStack(Material.DIAMOND_CHESTPLATE, 1);
		ItemStack DiamondL = new ItemStack(Material.DIAMOND_LEGGINGS, 1);
		ItemStack DiamondB = new ItemStack(Material.DIAMOND_BOOTS, 1);
		ItemStack Cobble = new ItemStack(Material.COBBLESTONE, 48);
		ItemStack fire2 = new ItemStack(Material.LAVA_BUCKET, 1);
		ItemStack Wood = new ItemStack(Material.WOOD, 48);
		ItemStack water = new ItemStack(Material.WATER_BUCKET, 1);
		ItemStack GoldenHead2 = new ItemStack(Material.GOLDEN_APPLE, 2);
		ItemStack GoldenHead4 = new ItemStack(Material.GOLDEN_APPLE, 4);
		ItemStack GoldenHead6 = new ItemStack(Material.GOLDEN_APPLE, 6);

		ItemStack Gap2 = new ItemStack(Material.GOLDEN_APPLE, 2);

		ItemStack Gap4 = new ItemStack(Material.GOLDEN_APPLE, 4);
		ItemStack Gap6 = new ItemStack(Material.GOLDEN_APPLE, 6);
		ItemStack steak = new ItemStack(Material.COOKED_BEEF, 3);
		ItemStack gcarrot = new ItemStack(Material.GOLDEN_CARROT, 4);
		ItemStack melon = new ItemStack(Material.WORKBENCH, 1);
		ItemStack table = new ItemStack(Material.ENCHANTMENT_TABLE, 1);
		ItemStack anvil = new ItemStack(Material.ANVIL, 1);

		ItemStack gapple  = new ItemStack(Material.GOLDEN_APPLE, 1);
		ItemMeta ISwordMeta = SwordI.getItemMeta();
		ItemMeta DSwordMeta = SwordD.getItemMeta();
		ItemMeta SSwordMeta = SwordS.getItemMeta();
		ItemMeta BowMeta = Bow.getItemMeta();
		ItemMeta IronHMeta = SwordI.getItemMeta();
		ItemMeta IronCMeta = IronC.getItemMeta();
		ItemMeta IronLMeta = IronL.getItemMeta();
		ItemMeta IronBMeta = IronB.getItemMeta();
		ItemMeta DiamondHMeta = DiamondH.getItemMeta();
		ItemMeta DiamondCMeta = DiamondC.getItemMeta();
		ItemMeta DiamondLMeta = DiamondL.getItemMeta();
		ItemMeta DiamondBMeta = DiamondB.getItemMeta();
		ItemMeta GoldenHeadMeta = GoldenHead2.getItemMeta();
		ItemMeta GoldenHeadMeta4 = GoldenHead4.getItemMeta();
		ItemMeta GoldenHeadMeta6 = GoldenHead6.getItemMeta();

		// Random kit generator. 20 CURRENT KITS.
		Random object = new Random();
			int kit;
		for(int counter =1; counter<=1;counter++) {
			kit = 1+object.nextInt(20); 
			if(kit == 1) {
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().clear();
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap4);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
		}
			if(kit == 2) {
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,2,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().clear();
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(IronB);
			}
			if(kit == 3) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,2,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,3,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow8);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
			}
			if(kit == 4) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow36);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(DiamondB);
			}
			if(kit == 5) {
				player.getInventory().clear();
				SSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,3,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordS);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
			}
			if(kit == 6) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
			}
			if(kit == 7) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow36);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
			}
			if(kit == 8) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow36);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(DiamondB);
			}
			if(kit == 9) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead4);
				player.getInventory().addItem(gapple);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow36);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
			}
			if(kit == 10) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap4);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
	}
			if(kit == 11) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow8);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(IronB);
		}
			if(kit == 12) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,2,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap2);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
				
			}
			if(kit == 13) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,3,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(gapple);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow16);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(DiamondB);
				
			}
			if(kit == 14) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,2,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,3,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap4);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow36);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
				
			}
			if(kit == 15) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,2,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,3,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
				
			}
			if(kit == 16) {
				player.getInventory().clear();
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead4);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow16);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(IronB);
				
			}
			if(kit == 17) {
				player.getInventory().clear();
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				IronHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead6);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow16);
				player.getInventory().setHelmet(IronH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(DiamondB);
				
			}
			if(kit == 18) {
				DSwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().clear();
				player.getInventory().addItem(SwordD);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap6);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow24);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(DiamondC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
				
			}
			if(kit == 19) {
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				DiamondLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				IronBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,2,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,2,true);
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().clear();
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead2);
				player.getInventory().addItem(Gap4);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow16);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(DiamondL);
				player.getInventory().setBoots(IronB);
				
			}
			if(kit == 20) {
				ISwordMeta.addEnchant(Enchantment.DAMAGE_ALL,1,true);
				DiamondHMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				IronCMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				IronLMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,3,true);
				DiamondBMeta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,1,true);
				BowMeta.addEnchant(Enchantment.ARROW_DAMAGE,1,true);
				player.getInventory().clear();
				SwordI.setItemMeta(ISwordMeta);
				SwordD.setItemMeta(DSwordMeta);
				SwordS.setItemMeta(SSwordMeta);
				Bow.setItemMeta(BowMeta);
				IronH.setItemMeta(IronHMeta);
				IronC.setItemMeta(IronCMeta);
				IronL.setItemMeta(IronLMeta);
				IronB.setItemMeta(IronBMeta);
				DiamondH.setItemMeta(DiamondHMeta);
				DiamondC.setItemMeta(DiamondCMeta);
				DiamondL.setItemMeta(DiamondLMeta);
				DiamondB.setItemMeta(DiamondBMeta);
				GoldenHeadMeta.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta4.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHeadMeta6.setDisplayName(ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--" + ChatColor.RESET + "" + ChatColor.GOLD + "" + ChatColor.BOLD + "Golden Head" + "" + ChatColor.RESET + "" +ChatColor.MAGIC + "" + ChatColor.DARK_BLUE + "--");
				GoldenHead2.setItemMeta(GoldenHeadMeta);
				GoldenHead4.setItemMeta(GoldenHeadMeta4);
				GoldenHead6.setItemMeta(GoldenHeadMeta6);
				player.getInventory().addItem(SwordI);
				player.getInventory().addItem(Rod);
				player.getInventory().addItem(fire2);
				player.getInventory().addItem(Bow);
				player.getInventory().addItem(water);
				player.getInventory().addItem(Cobble);
				player.getInventory().addItem(Wood);
				player.getInventory().addItem(GoldenHead4);
				player.getInventory().addItem(Gap4);
				// head
				player.getInventory().addItem(table);
				player.getInventory().addItem(anvil);
				player.getInventory().setItem(12, Arrow16);
				player.getInventory().setHelmet(DiamondH);
				player.getInventory().setChestplate(IronC);
				player.getInventory().setLeggings(IronL);
				player.getInventory().setBoots(DiamondB);
				}


		}
	}
}
	
	


